arb-dir: l10n
output-dir: lib/presentation/l10n
template-arb-file: intl_en.arb
output-class: L10n
output-localization-file: l10n.dart
preferred-supported-locales: [ en ]
nullable-getter: false
format: true
header: "// dart format off"
