# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Push a new beta build to the Mob track"
  lane :beta do
    begin
      upload_to_play_store(
        track: 'beta',
        aab: '../build/app/outputs/bundle/prodRelease/app-prod-release.aab',
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        release_status: "draft",
      )
    end
  end
end
